/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.EPC;
import Model.EPCDAO;
import static java.awt.image.ImageObserver.HEIGHT;
import javax.swing.JOptionPane;

/**
 *
 * @author antun
 */
public class TelaCadastroEPC extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroEPC
     */
    public TelaCadastroEPC() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        EntradaTextoNomeEPC = new javax.swing.JTextField();
        EntradaTextoNumeroSerieEPC = new javax.swing.JTextField();
        BotaoCancelarCadastroEPI = new javax.swing.JButton();
        BotaoVoltarCadastroFuncionario = new javax.swing.JButton();
        BotaoCadastroEPI = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuCadastrar2 = new javax.swing.JMenu();
        MenuCadastrarFuncionario2 = new javax.swing.JMenuItem();
        MenuCadastrarFerramenta2 = new javax.swing.JMenuItem();
        MenuCadastrarEPI2 = new javax.swing.JMenuItem();
        MenuCadastrarEPC2 = new javax.swing.JMenuItem();
        MenuListar2 = new javax.swing.JMenu();
        MenuListarFuncionario2 = new javax.swing.JMenuItem();
        MenuListarFerramenta2 = new javax.swing.JMenuItem();
        MenuListarEPI2 = new javax.swing.JMenuItem();
        MenuListarEPC2 = new javax.swing.JMenuItem();
        MenuAtualizar2 = new javax.swing.JMenu();
        MenuAtualizarFuncionario2 = new javax.swing.JMenuItem();
        MenuAtualizarFerramenta2 = new javax.swing.JMenuItem();
        MenuAtualizarEPI2 = new javax.swing.JMenuItem();
        MenuAtualizarEPC2 = new javax.swing.JMenuItem();
        MenuDeletar2 = new javax.swing.JMenu();
        MenuDeletarFuncionario2 = new javax.swing.JMenuItem();
        MenuDeletarFerramenta2 = new javax.swing.JMenuItem();
        MenuDeletarEPI2 = new javax.swing.JMenuItem();
        MenuDeletarEPC2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        EntradaTextoNomeEPC.setBorder(javax.swing.BorderFactory.createTitledBorder("Nome EPC"));

        EntradaTextoNumeroSerieEPC.setBorder(javax.swing.BorderFactory.createTitledBorder("Numero de Serie do EPC"));

        BotaoCancelarCadastroEPI.setText("Cancelar");
        BotaoCancelarCadastroEPI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCancelarCadastroEPIActionPerformed(evt);
            }
        });

        BotaoVoltarCadastroFuncionario.setText("Voltar");
        BotaoVoltarCadastroFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoVoltarCadastroFuncionarioActionPerformed(evt);
            }
        });

        BotaoCadastroEPI.setText("Cadastrar");
        BotaoCadastroEPI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCadastroEPIActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EntradaTextoNomeEPC)
                    .addComponent(EntradaTextoNumeroSerieEPC, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BotaoCadastroEPI)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BotaoVoltarCadastroFuncionario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BotaoCancelarCadastroEPI, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EntradaTextoNomeEPC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(EntradaTextoNumeroSerieEPC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoCancelarCadastroEPI)
                    .addComponent(BotaoCadastroEPI))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 235, Short.MAX_VALUE)
                .addComponent(BotaoVoltarCadastroFuncionario)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        MenuCadastrar2.setText("Cadastrar");

        MenuCadastrarFuncionario2.setText("Funcionario");
        MenuCadastrarFuncionario2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCadastrarFuncionario2ActionPerformed(evt);
            }
        });
        MenuCadastrar2.add(MenuCadastrarFuncionario2);

        MenuCadastrarFerramenta2.setText("Ferramenta");
        MenuCadastrarFerramenta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCadastrarFerramenta2ActionPerformed(evt);
            }
        });
        MenuCadastrar2.add(MenuCadastrarFerramenta2);

        MenuCadastrarEPI2.setText("EPI");
        MenuCadastrarEPI2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCadastrarEPI2ActionPerformed(evt);
            }
        });
        MenuCadastrar2.add(MenuCadastrarEPI2);

        MenuCadastrarEPC2.setText("EPC");
        MenuCadastrarEPC2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCadastrarEPC2ActionPerformed(evt);
            }
        });
        MenuCadastrar2.add(MenuCadastrarEPC2);

        jMenuBar1.add(MenuCadastrar2);

        MenuListar2.setText("Listar");

        MenuListarFuncionario2.setText("Funcionario");
        MenuListarFuncionario2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuListarFuncionario2ActionPerformed(evt);
            }
        });
        MenuListar2.add(MenuListarFuncionario2);

        MenuListarFerramenta2.setText("Ferramenta");
        MenuListarFerramenta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuListarFerramenta2ActionPerformed(evt);
            }
        });
        MenuListar2.add(MenuListarFerramenta2);

        MenuListarEPI2.setText("EPI");
        MenuListarEPI2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuListarEPI2ActionPerformed(evt);
            }
        });
        MenuListar2.add(MenuListarEPI2);

        MenuListarEPC2.setText("EPC");
        MenuListarEPC2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuListarEPC2ActionPerformed(evt);
            }
        });
        MenuListar2.add(MenuListarEPC2);

        jMenuBar1.add(MenuListar2);

        MenuAtualizar2.setText("Atualizar");

        MenuAtualizarFuncionario2.setText("Funcionario");
        MenuAtualizarFuncionario2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAtualizarFuncionario2ActionPerformed(evt);
            }
        });
        MenuAtualizar2.add(MenuAtualizarFuncionario2);

        MenuAtualizarFerramenta2.setText("Ferramenta");
        MenuAtualizarFerramenta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAtualizarFerramenta2ActionPerformed(evt);
            }
        });
        MenuAtualizar2.add(MenuAtualizarFerramenta2);

        MenuAtualizarEPI2.setText("EPI");
        MenuAtualizarEPI2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAtualizarEPI2ActionPerformed(evt);
            }
        });
        MenuAtualizar2.add(MenuAtualizarEPI2);

        MenuAtualizarEPC2.setText("EPC");
        MenuAtualizarEPC2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAtualizarEPC2ActionPerformed(evt);
            }
        });
        MenuAtualizar2.add(MenuAtualizarEPC2);

        jMenuBar1.add(MenuAtualizar2);

        MenuDeletar2.setText("Deletar");

        MenuDeletarFuncionario2.setText("Funcionario");
        MenuDeletarFuncionario2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuDeletarFuncionario2ActionPerformed(evt);
            }
        });
        MenuDeletar2.add(MenuDeletarFuncionario2);

        MenuDeletarFerramenta2.setText("Ferramenta");
        MenuDeletarFerramenta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuDeletarFerramenta2ActionPerformed(evt);
            }
        });
        MenuDeletar2.add(MenuDeletarFerramenta2);

        MenuDeletarEPI2.setText("EPI");
        MenuDeletarEPI2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuDeletarEPI2ActionPerformed(evt);
            }
        });
        MenuDeletar2.add(MenuDeletarEPI2);

        MenuDeletarEPC2.setText("EPC");
        MenuDeletarEPC2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuDeletarEPC2ActionPerformed(evt);
            }
        });
        MenuDeletar2.add(MenuDeletarEPC2);

        jMenuBar1.add(MenuDeletar2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuCadastrarFuncionario2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCadastrarFuncionario2ActionPerformed
        TelaCadastroFuncionario t = new TelaCadastroFuncionario();
        t.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_MenuCadastrarFuncionario2ActionPerformed

    private void MenuCadastrarFerramenta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCadastrarFerramenta2ActionPerformed
        TelaCadastroFerramenta t = new TelaCadastroFerramenta();
        t.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_MenuCadastrarFerramenta2ActionPerformed

    private void MenuCadastrarEPI2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCadastrarEPI2ActionPerformed
        TelaCadastroEPI t = new TelaCadastroEPI();
        t.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_MenuCadastrarEPI2ActionPerformed

    private void MenuCadastrarEPC2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCadastrarEPC2ActionPerformed
        TelaCadastroEPC t = new TelaCadastroEPC();
        t.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_MenuCadastrarEPC2ActionPerformed

    private void MenuListarFuncionario2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuListarFuncionario2ActionPerformed
        TelaListarFuncionario t = new TelaListarFuncionario();
        t.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_MenuListarFuncionario2ActionPerformed

    private void MenuListarFerramenta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuListarFerramenta2ActionPerformed
        TelaListarFerramenta t = new TelaListarFerramenta();
        t.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_MenuListarFerramenta2ActionPerformed

    private void MenuListarEPI2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuListarEPI2ActionPerformed
        TelaListarEPI t = new TelaListarEPI();
        t.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_MenuListarEPI2ActionPerformed

    private void MenuListarEPC2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuListarEPC2ActionPerformed
        TelaListarEPC t = new TelaListarEPC();
        t.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_MenuListarEPC2ActionPerformed

    private void MenuAtualizarFuncionario2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAtualizarFuncionario2ActionPerformed
        TelaAtualizarFuncionario t = new TelaAtualizarFuncionario();
        t.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_MenuAtualizarFuncionario2ActionPerformed

    private void MenuAtualizarFerramenta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAtualizarFerramenta2ActionPerformed
        TelaAtualizarFerramenta t = new TelaAtualizarFerramenta();
        t.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_MenuAtualizarFerramenta2ActionPerformed

    private void MenuAtualizarEPI2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAtualizarEPI2ActionPerformed
        TelaAtualizarEPI t = new TelaAtualizarEPI();
        t.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_MenuAtualizarEPI2ActionPerformed

    private void MenuAtualizarEPC2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAtualizarEPC2ActionPerformed
        TelaAtualizarEPC t = new TelaAtualizarEPC();
        t.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_MenuAtualizarEPC2ActionPerformed

    private void MenuDeletarFuncionario2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuDeletarFuncionario2ActionPerformed
        TelaDeletarFuncionario t = new TelaDeletarFuncionario();
        t.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_MenuDeletarFuncionario2ActionPerformed

    private void MenuDeletarFerramenta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuDeletarFerramenta2ActionPerformed
        TelaDeletarFerramenta t = new TelaDeletarFerramenta();
        t.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_MenuDeletarFerramenta2ActionPerformed

    private void MenuDeletarEPI2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuDeletarEPI2ActionPerformed
        TelaDeletarEPI t = new TelaDeletarEPI();
        t.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_MenuDeletarEPI2ActionPerformed

    private void MenuDeletarEPC2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuDeletarEPC2ActionPerformed
        TelaDeletarEPC t = new TelaDeletarEPC();
        t.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_MenuDeletarEPC2ActionPerformed

    private void BotaoCancelarCadastroEPIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCancelarCadastroEPIActionPerformed
        EntradaTextoNomeEPC.setText("");
        EntradaTextoNumeroSerieEPC.setText("");
    }//GEN-LAST:event_BotaoCancelarCadastroEPIActionPerformed

    private void BotaoVoltarCadastroFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoVoltarCadastroFuncionarioActionPerformed
        TelaInicial t = new TelaInicial();
        t.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotaoVoltarCadastroFuncionarioActionPerformed

    private void BotaoCadastroEPIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCadastroEPIActionPerformed
        EPC epc = new EPC(
            Integer.parseInt(EntradaTextoNumeroSerieEPC.getText()),
            EntradaTextoNomeEPC.getText());

        EPCDAO epidao = new EPCDAO();
        if(!epidao.buscarEPCSemFiltro().contains(Integer.parseInt(EntradaTextoNumeroSerieEPC.getText()))) {
            epidao.inserirEPC(epc);
            System.out.println("Cadastrado");
        } else {
            System.out.println("EPC ja cadastrado");
        }
        
        JOptionPane.showMessageDialog(null, "Cadastro Confirmado", null, HEIGHT);
        
        EntradaTextoNomeEPC.setText("");
        EntradaTextoNumeroSerieEPC.setText("");
    }//GEN-LAST:event_BotaoCadastroEPIActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroEPC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroEPC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroEPC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroEPC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroEPC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoCadastroEPI;
    private javax.swing.JButton BotaoCancelarCadastroEPI;
    private javax.swing.JButton BotaoVoltarCadastroFuncionario;
    private javax.swing.JTextField EntradaTextoNomeEPC;
    private javax.swing.JTextField EntradaTextoNumeroSerieEPC;
    private javax.swing.JMenu MenuAtualizar2;
    private javax.swing.JMenuItem MenuAtualizarEPC2;
    private javax.swing.JMenuItem MenuAtualizarEPI2;
    private javax.swing.JMenuItem MenuAtualizarFerramenta2;
    private javax.swing.JMenuItem MenuAtualizarFuncionario2;
    private javax.swing.JMenu MenuCadastrar2;
    private javax.swing.JMenuItem MenuCadastrarEPC2;
    private javax.swing.JMenuItem MenuCadastrarEPI2;
    private javax.swing.JMenuItem MenuCadastrarFerramenta2;
    private javax.swing.JMenuItem MenuCadastrarFuncionario2;
    private javax.swing.JMenu MenuDeletar2;
    private javax.swing.JMenuItem MenuDeletarEPC2;
    private javax.swing.JMenuItem MenuDeletarEPI2;
    private javax.swing.JMenuItem MenuDeletarFerramenta2;
    private javax.swing.JMenuItem MenuDeletarFuncionario2;
    private javax.swing.JMenu MenuListar2;
    private javax.swing.JMenuItem MenuListarEPC2;
    private javax.swing.JMenuItem MenuListarEPI2;
    private javax.swing.JMenuItem MenuListarFerramenta2;
    private javax.swing.JMenuItem MenuListarFuncionario2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
